In [1]:
import numpy as np
import pandas as pd

In [2]:
my_list = [1,'Corolado',4.7]

In [3]:
my_list

[1, 'Corolado', 4.7]

In [4]:
my_list[0]

1

In [5]:
my_list[-1]

4.7

In [6]:
my_array = np.array([1,2,3])
my_array

array([1, 2, 3])

In [7]:
my_array[0]

1

In [8]:
# the elements of the numpy array are of the same data type. python list could be different data type. numpy array will save memory

In [9]:
my_array = np.array([1,2,3])
my_list = [1,2,3]

In [10]:
my_array/3

array([0.33333333, 0.66666667, 1.        ])

In [13]:
# list will get error, list do not support this kind of operation
# my_list/3

In [14]:
# Append
my_list.append('new thing')
my_list

[1, 2, 3, 'new thing']

In [18]:
my_array = np.append(my_array, 5)
my_array

array([1, 2, 3, 5, 5])

In [20]:
# Dictionary
my_dict = {'key1':'first value','key2':'second value'}

In [23]:
my_dict['key1']

'first value'

In [24]:
my_dict['new key'] = 'new value'

In [25]:
my_dict['new key']

'new value'

In [26]:
df = pd.DataFrame({'col1':range(0,3),'col2':range(3,6)})
df

col1  col2
0     0     3
1     1     4
2     2     5

In [30]:
df.rename(columns={'col1':'apple','col2':'banana'})

apple  banana
0      0       3
1      1       4
2      2       5